export const SET_SPECTRUM_RANGE = 'SET_SPECTRUM_RANGE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_CHANNEL_SET = 'SET_IS_CHANNEL_SET';
export const SET_CHANNEL_LIST = 'SET_CHANNEL_LIST';
export const PLAY_SPECTRUM_STREAM = 'PLAY_SPECTRUM_STREAM';
export const PAUSE_SPECTRUM_STREAM = 'PAUSE_SPECTRUM_STREAM';
export const PLAY_WNDETECTOR_STREAM = 'PLAY_WNDETECTOR_STREAM';
export const PAUSE_WNDETECTOR_STREAM = 'PAUSE_WNDETECTOR_STREAM';
export const PLAY_DIFFDETECTOR_STREAM = 'PLAY_DIFFDETECTOR_STREAM';
export const PAUSE_DIFFDETECTOR_STREAM = 'PAUSE_DIFFDETECTOR_STREAM';
export const CLEAR_SNAPSHOTS = 'CLEAR_SNAPSHOTS';
export const PLAY_DDC_DATA_STREAM = 'PLAY_DDC_DATA_STREAM';
export const PAUSE_DDC_DATA_STREAM = 'PAUSE_DDC_DATA_STREAM';
export const SET_ADDING_PROBE_DIALOG_VISIBILITY = 'SET_ADDING_PROBE_DIALOG_VISIBILITY';
export const ADD_SERVER_PROBE = 'ADD_SERVER_PROBE';
export const DELETE_SERVER_PROBE = 'DELETE_SERVER_PROBE';
export const LOAD_SERVER_PROBES = 'LOAD_SERVER_PROBES';
export const UPDATE_GRAPH_SETTINGS = 'UPDATE_GRAPH_SETTINGS';
export const UPDATE_PROBE_SETTINGS = 'UPDATE_PROBE_SETTINGS';
export const LOAD_GRAPH_SETTINGS = 'LOAD_GRAPH_SETTINGS';
export const LOAD_BACKEND_INFO = 'LOAD_BACKEND_INFO';

//api_settings page
export const SET_API_IP_ADDRESS = 'SET_API_IP_ADDRESS';
export const SET_API_PORT_NUMBER = 'SET_API_PORT_NUMBER';

export const PLAY_PROBE_STREAM = 'PLAY_PROBE_STREAM';
export const PAUSE_PROBE_STREAM = 'PAUSE_PROBE_STREAM';
export const START_FETCH_PROBE_SNAPSHOT = 'START_FETCH_PROBE_SNAPSHOT';
